# Logger mag FINER en hoger doorlaten
.level=FINER

# Twee handlers:
# 1. console
# 2. bestand
handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler


# =========================
# ConsoleHandler
# =========================

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter


# =========================
# FileHandler
# =========================

java.util.logging.FileHandler.level=FINE

# Bestand in je home-directory:
# java0.log, java1.log, ...
java.util.logging.FileHandler.pattern=%h/java%g.log

# Maximum 1 MB per bestand
java.util.logging.FileHandler.limit=1000000

# Maximum 4 bestanden
java.util.logging.FileHandler.count=4

# Bestand standaard in XML-formaat
java.util.logging.FileHandler.formatter=java.util.logging.XMLFormatter